package com.agentic.riskai.ro.model;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

public class DocumentEmbedding {

    private String content;
    private String contentType;
    private List<Double> embedding;
    private Map<String, Object> metadata;
    private LocalDateTime createdAt;

    public DocumentEmbedding(String content, String contentType, List<Double> embedding, Map<String, Object> metadata, LocalDateTime createdAt) {
        this.content = content;
        this.contentType = contentType;
        this.embedding = embedding;
        this.metadata = metadata;
        this.createdAt = createdAt;
    }

    // Getters and setters can be generated by Lombok's @Data annotation
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public List<Double> getEmbedding() {
        return embedding;
    }

    public void setEmbedding(List<Double> embedding) {
        this.embedding = embedding;
    }

    public Map<String, Object> getMetadata() {
        return metadata;
    }

    public void setMetadata(Map<String, Object> metadata) {
        this.metadata = metadata;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
